###
GET http://localhost:8080

###
GET http://api.localhost:8080/323213

###
POST http://api.localhost:8080/register
content-type: application/json

{
    "userName": "exaMPle_test5",
    "password": "password-05"
}

###
POST http://api.localhost:8080/login

###
GET http://api.localhost:8080/logout

###
GET http://api.localhost:8080/refesh-token